// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCilJFJhpqKg_gmAr49eedtM-ApjwMVcMk',
    appId: '1:840943454960:web:b5b795c4ce1088d4f15035',
    messagingSenderId: '840943454960',
    projectId: 'babeit',
    authDomain: 'babeit.firebaseapp.com',
    storageBucket: 'babeit.appspot.com',
    measurementId: 'G-3PGTGHMKE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYEpBj9TyYbL04IP68Rq_3T9Da1B_iMoI',
    appId: '1:840943454960:android:2aa2f6bc58cb6914f15035',
    messagingSenderId: '840943454960',
    projectId: 'babeit',
    storageBucket: 'babeit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn9xEv7DC5UrKMU-aJfP9tuUi-hD2V8jQ',
    appId: '1:840943454960:ios:689761db8fe372e3f15035',
    messagingSenderId: '840943454960',
    projectId: 'babeit',
    storageBucket: 'babeit.appspot.com',
    iosClientId: '840943454960-eh74keoh1ur9stq2rq81i011jo3k4q10.apps.googleusercontent.com',
    iosBundleId: 'com.example.babeIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn9xEv7DC5UrKMU-aJfP9tuUi-hD2V8jQ',
    appId: '1:840943454960:ios:689761db8fe372e3f15035',
    messagingSenderId: '840943454960',
    projectId: 'babeit',
    storageBucket: 'babeit.appspot.com',
    iosClientId: '840943454960-eh74keoh1ur9stq2rq81i011jo3k4q10.apps.googleusercontent.com',
    iosBundleId: 'com.example.babeIt',
  );
}
